### ISSUE TITLE
DeprecationWarning: Buffer() 

### ISSUE THREAD

**Issue by stevenwhayes** [hashicorp/setup-terraform#183]
Getting warning when running this action:
`(node:1781) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:186:11)
    at new Buffer (node:buffer:270:3)
    at Object.9203 (/home/runner/work/_actions/hashicorp/setup-terraform/main/dist/index.js:40921:17)
    at __nccwpck_require__ (/home/runner/work/_actions/hashicorp/setup-terraform/main/dist/index.js:69632:43)
    at Object.9886 (/home/runner/work/_actions/hashicorp/setup-terraform/main/dist/index.js:423[16](https://github.com/department-of-veterans-affairs/bedrock-infrastructure/runs/6082561465?check_suite_focus=true#step:4:16):31)
    at __nccwpck_require__ (/home/runner/work/_actions/hashicorp/setup-terraform/main/dist/index.js:69632:43)
    at Object.[17](https://github.com/department-of-veterans-affairs/bedrock-infrastructure/runs/6082561465?check_suite_focus=true#step:4:17)92 (/home/runner/work/_actions/hashicorp/setup-terraform/main/dist/index.js:42691:31)
    at __nccwpck_require__ (/home/runner/work/_actions/hashicorp/setup-terraform/main/dist/index.js:69632:43)
    at Object.6338 (/home/runner/work/_actions/hashicorp/setup-terraform/main/dist/index.js:48876:35)
    at __nccwpck_require__ (/home/runner/work/_actions/hashicorp/setup-terraform/main/dist/index.js:69632:43)`

VSCode showing it on lines 37869 and 40921 of index.js

Saw this partially addressed in https://github.com/hashicorp/setup-terraform/pull/76

**Comment by chenrui333** [comment]
This would be ncc issue, https://github.com/vercel/ncc/issues/484
